repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: name-tests-test
  - repo: 'https://github.com/psf/black'
    rev: 24.4.2
    hooks:
      - id: black
        args:
          - '-l 120'
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length=120'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
        - --ignore-missing-imports
        - --explicit-package-bases
