# Generated by Django 5.0.3 on 2024-04-14 13:35

import django.db.models.deletion
import learning_paths.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("learning_paths", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitynode",
            options={
                "verbose_name": "Activity Node",
                "verbose_name_plural": "Activity Nodes",
            },
        ),
        migrations.AlterModelOptions(
            name="badgenode",
            options={
                "verbose_name": "Badge Node",
                "verbose_name_plural": "Badge Nodes",
            },
        ),
        migrations.AddField(
            model_name="activitynode",
            name="content_type",
            field=models.ForeignKey(
                default=learning_paths.models.get_default_content_type,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activitynode",
            name="object_id",
            field=models.PositiveIntegerField(
                default=learning_paths.models.get_default_content_type
            ),
        ),
        migrations.AddField(
            model_name="badgenode",
            name="content_type",
            field=models.ForeignKey(
                default=learning_paths.models.get_default_content_type,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="badgenode",
            name="object_id",
            field=models.PositiveIntegerField(
                default=learning_paths.models.get_default_content_type
            ),
        ),
        migrations.AlterField(
            model_name="activitynode",
            name="learning_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_paths.learningpath",
            ),
        ),
        migrations.AlterField(
            model_name="badgenode",
            name="learning_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_paths.learningpath",
            ),
        ),
    ]
